#!/bin/bash
echo "========================================="
echo "   Lnm-Brain Second Brain Setup Guide    "
echo "========================================="
echo ""
echo "This repository is fully cloud-native. You do not need to do anything locally to run it."
echo "Your AI assistants (OpenCode, Claude Code) will communicate with it via the Cloudflare Worker."
echo ""
echo "--- Viewing in the Browser ---"
echo "You can view your entire knowledge graph visually in any browser:"
echo "👉 https://your-worker-subdomain.workers.dev/"
echo ""
echo "--- Viewing in Obsidian (Desktop) ---"
echo "1. Open Obsidian"
echo "2. Select 'Open folder as vault'"
echo "3. Choose this directory"
echo ""
echo "--- Viewing in Obsidian (Mobile - iOS/Android) ---"
echo "1. Install the Obsidian app on your phone."
echo "2. Clone this repository to your phone:"
echo "   - iOS: Use 'Working Copy' app to clone, then link the folder to Obsidian."
echo "   - Android: Use Termux to clone, then open the folder in Obsidian."
echo "3. The Obsidian Git plugin is already pre-configured in this repo."
echo "   It will automatically pull changes when you open the app, and push backups every 10 minutes."
echo ""
echo "Setup complete! You're ready to use your Second Brain."
